#requires -RunAsAdministrator
<#
    .NOTES
    --------------------------------------------------------------------------------
    Code generated by:  Hands
    Generated on:       20/05/2018
    Generated by:       Guillaume Mateos
    Organization:       Shell Networks
    --------------------------------------------------------------------------------
    .SYNOPSIS
    Use this script to create the no sms on drive file
    .DESCRIPTION
    Create the file on each disk on wich you dont want SCCM to install files
#>

#region Variables
$NoSmsDisks = @("C","D","S") #here you put disks on wich you dont want
#endregion

#region Functions
function Set-NoSmsOnDrive
{   
     <#
        .SYNOPSIS
        Create the file no_sms_on_drive.sms on choosen drives
        .DESCRIPTION
        The file will be created at the root of choosen drives
        .PARAMETER Drives
        Drives on wich you want the file to be created
        .EXAMPLE
        Set-NoSmsOnDrive -Drives "C","D"
    #>
    [Cmdletbinding()]
    Param (
    [Parameter(Mandatory = $True,Position = 0)]
    [String[]]
    $Drives
    )
    
    $FileToCreate = "no_sms_on_drive.sms"

    foreach($Drive in $Drives)
    {
        Write-Host -ForegroundColor Cyan "Creating $($FileToCreate) on $($Drive) drive"

        $Create = $True
        try 
        {
            New-Item -ItemType File -Name $FileToCreate -Path "$($Drive):\" -Force -ErrorAction Stop
        }
        catch 
        {
            Write-Host -ForegroundColor Red "Error writing $($FileToCreate) on $($Drive)"
            $Create = $false
        }

        if($Create)
        {
            Write-Host -ForegroundColor Green "File creation OK"
        }
    }   
}
#endregion

#region Script

Set-NoSmsOnDrive -Drives $NoSmsDisks

#endregion