<#
    .NOTES
    --------------------------------------------------------------------------------
    Code generated by:  Hands
    Generated on:       13/05/2018
    Generated by:       Guillaume Mateos
    Organization:       SHell Networks
    --------------------------------------------------------------------------------
    .SYNOPSIS
    Automatic Installation of ReportViewer for the SCCM Site Server
    Automatic Installation of ADK for Windows 8.1 for the SCCM Site Server
    .DESCRIPTION

#>

$ReportViewerExePath = "C:\ReportViewer.exe" #Indicate there where is stored the .exe
$ADKExePath = "C:\adksetup.exe" #Indicate there where is stored the .exe

& $ReportViewerExePath Setup /passive /promptrestart /showfinalerror

& $ADKExePath /features OptionId.DeploymentTools OptionId.WindowsPreinstallationEnvironment OptionId.UserStateMigrationTool `
/installpath "C:\Program Files (x86)\Windows Kits\8.1\" /ceip off