<#
    .NOTES
    --------------------------------------------------------------------------------
    Code generated by:  Hands
    Generated on:       19/05/2018
    Generated by:       Guillaume Mateos
    Organization:       SHell Networks
    --------------------------------------------------------------------------------
    .SYNOPSIS
    Use this script before lauching sccm install to check prerequisites
    .DESCRIPTION
    Has to be run from the site server computer 

#>

$ScmmPrerequPath = "C:\SMSSETUP\BIN\X64\prereqchk.exe" #Indicate there where is stored the .exe

& $ScmmPrerequPath /AdminUI

 