<#
    .NOTES
    --------------------------------------------------------------------------------
    Code generated by:  Hands
    Generated on:       20/05/2018
    Generated by:       Guillaume Mateos
    Organization:       SHell Networks
    --------------------------------------------------------------------------------
    .SYNOPSIS
    Use this script to perform installation of sccm primary site
    .DESCRIPTION
    Has to be run from the site server computer 

#>

$ScmmSetupPath = "C:\SMSSETUP\BIN\X64\setup.exe" #Indicate there where is stored the .exe
$ScmmSetupFilePath = "C:\07-SCCM-ConfigurationFile.ini" #Indicate there where is stored the .exe

& $ScmmSetupPath /NOUSERINPUT /SCRIPT $ScmmSetupFilePath

 